### ISSUE TITLE
Update package on Chocolatey.org

### ISSUE THREAD

**Issue by gsmitheidw** [Waikato/weka-wiki#3]
Hi, 

The version on Chocolatey.org seems to be pretty much abandoned at version 3.6.9.002:

https://community.chocolatey.org/packages/weka

Could this be updated please to 3.8.5 ? 

The existing chocolatey package is also an older style that lacks modern features such as checksums, links to the source etc, so this would be beneficial for security as well. 

Many thanks,

Graham

**Comment by fracpete** [comment]
The choc package is not officially maintained by the Weka team. You'd have to contact the maintainer instead.

**Comment by gsmitheidw** [comment]
Oh apologies, I misread maintainer/authors on the package website, Many thanks for responding anyway!
