### ISSUE TITLE
changing default class color in pre-processing tab

### ISSUE THREAD

**Issue by yuliaUU** [Waikato/weka-wiki#7]
Is there a way to  change default class color in pre-processing tab? I know we can do it through Visualize panel, but

**Comment by fracpete** [comment]
Are you referring to the colors of the histogram (bottom right on the Preprocessing panel)? Those are hard-coded in the `weka.gui.AttributeVisualizationPanel` class.

**Comment by fracpete** [comment]
BTW The latest snapshot of [ADAMS](https://adams.cms.waikato.ac.nz/download/snapshot/) allows you to customize the colors used in the attribute summary panel of the **Weka Investigator**:

![Investigator_001](https://github.com/Waikato/weka-wiki/assets/1026180/1ef73d02-c64e-4d3f-9a2f-5683f0111612)

**NB:** The **Weka Investigator** is a more powerful version of the Weka Explorer.

**Comment by yuliaUU** [comment]
thank ypu for your reply! how do i install the snapshot so it becomes available in WEKA investigator?

**Comment by fracpete** [comment]
You just download the snapshot zip file, decompress it, and run it. Nothing else to do.
If you want Weka, you need to download the adams-ml-app snapshot. Weka is part of ADAMS, not the other way around. :-)

**Comment by yuliaUU** [comment]
got it! thank you
